# This file contains values from Cookiecutter

default_context:
  project_name: "ifellow-test-case"
  project_description: "Test case for iFellow QA Automation junior course"
  organization: "Fedor Zlobin"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "mrfz"
  email: "zlobin.f@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
